### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by seanwangsalad** [piercelab/tcrmodel2#18]
Ubuntu 22.04
CUDA 11.8 
AF 2.3

Dear developers,
When running the following command, I get the following errors:
sudo singularity build tcrmodel2.sif singularity/tcrmodel2_singularity.def
<img width="629" alt="Screenshot 2024-03-16 at 10 35 12 PM" src="https://github.com/piercelab/tcrmodel2/assets/73306167/e96f6f08-9a93-4eec-a450-fb958af68dec">

<img width="1068" alt="Screenshot 2024-03-16 at 10 31 13 PM" src="https://github.com/piercelab/tcrmodel2/assets/73306167/afb7f81c-9376-46a7-8a02-2f3f28b54120">

However it still builds thetcrmodel2.sif file.

However when I do:
_bash run_tcrmodel2_singularity.sh_
It returns the error:
Traceback (most recent call last):
  File "/opt/tcrmodel2/run_tcrmodel2.py", line 9, in <module>
    from absl import app, flags
ModuleNotFoundError: No module named 'absl'

Would really appreciate some help in figuring out if this is an installation or run error.

**Comment by rui-yin** [comment]
Hi Sean, 

Indeed, from the output you shared, it looks like the singularity container is not properly built (that's why you see the module not found error when running the bash script). The error message seems to have come from the cuda 23.5.0 not being compatible with python 3.12. However, in the tcrmodel2_singularity.def file, the Python version we specified is Python 3.10 (see this [line](https://github.com/piercelab/tcrmodel2/blob/dbe68c2e8f1a26ad2b40aefccc957b3f78677536/singularity/tcrmodel2_singularity.def#L40)).

Maybe you can double-check the Python version in the tcrmodel2_singularity.def file?

Best,
Rui

**Comment by seanwangsalad** [comment]
Hi Rui, should I specify 3.12? It is 3.10 in the .def file. Error seems to be coming from pin-1 

Thanks,
- Sean

**Comment by rui-yin** [comment]
Hi Sean, 

I think 3.10 is what you want, not 3.12. So what you have in the .def looks good. It's interesting that what you specify (python version 3.10) is different from what's being installed. 

Maybe try changing line 38 from:
conda install -qy conda==23.5.0 \

to:
conda install -qy conda==23.5.0 python=3.10 \

and everything else stays the same. 

Let me know how it goes! 

Best,
Rui

**Comment by bsaleme** [comment]
Hello Rui, I have also run into the same problem listed above. I have made the change you recommended (specifying the python version after conda version) and I successfully built the image but then I run into another issue with "jax.extend" module not being found. I added a picture of the error below. Any recommendations ? 


<img width="1247" alt="Screen Shot 2024-05-02 at 2 59 48 PM" src="https://github.com/piercelab/tcrmodel2/assets/57045822/43d3e342-a504-42d1-b47d-2a9c458d6f0f">

**Comment by bpierce12** [comment]
@bsaleme it looks like your issue is the same as what others have noted for ColabFold, and is related to the jax version:
https://github.com/YoshitakaMo/localcolabfold/issues/212
Downgrading to jaxlib to 0.4.23, as noted in that thread, will hopefully help with that problem.

**Comment by andreas-wilm** [comment]
Hi All,

All the above is at least partly caused, because the definitions file uses `Miniconda3-latest-Linux-x86_64.sh`, which changes over time. I just ran into similar problems and solved it by simply changing to an older Miniconda version, namely `Miniconda3-py310_23.11.0-2-Linux-x86_64.sh`. A diff looks as follows:
```
+#MINICONDA_VERSION=Miniconda3-latest-Linux-x86_64.sh
+MINICONDA_VERSION=Miniconda3-py310_23.11.0-2-Linux-x86_64.sh
 wget -P /tmp \
-    "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" \
-    && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
-    && rm /tmp/Miniconda3-latest-Linux-x86_64.sh
+    "https://repo.anaconda.com/miniconda/$MINICONDA_VERSION" \
+    && bash /tmp/$MINICONDA_VERSION -b -p /opt/conda \
+    && rm /tmp/$MINICONDA_VERSION
```

Best

**Comment by andreas-wilm** [comment]
Hi all,

I also ended in version dependency hell as well while upgrading the other day. The real culprit is that the definitions file always pulls the latest Alphafold commit. It's best to go with a certain commit/tag/release and then change library versions as needed. One (official) example is [this GCP Dockerfile](https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline/blob/main/Alphafold.dockerfile).

I ended up changing the TCRModel2 definitions file accordingly (conda 24.1.2, jax 0.4.13, cuda 11.8 and AF commit 032e2f2 from Feb 2024). Happy to share the file or issue a PR if of interest.

Andreas

**Comment by bsaleme** [comment]
@andreas-wilm mind if you share the definition file ? or the singularity image you built ? thanks!

**Comment by bpierce12** [comment]
Thanks @andreas-wilm for the notes regarding the fix for the definitions file. We have updated the definitions accordingly, generating two definitions files corresponding to two CUDA versions, both of which worked in our tests.

I'm closing this issue for now, but let us know if there are any more questions or issues associated with this.

**Comment by andreas-wilm** [comment]
Great! @bsaleme, PM me if you still need help
